[package]
name = "kanari-api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
log = { workspace = true }
kanari-oracle = { workspace = true }