[package]
name = "kanari-oracle"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json.workspace = true
serde.workspace = true
reqwest.workspace = true
chrono.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures.workspace = true